#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 03:26:39 2019

@author: Marco Baturan

@ Description: Computer program for simulation of cellular automaton based in
web : https://blog.adrianistan.eu/automatas-celulares-unidimensionales-python
and the definition of spanish version fo Wikipedia.
Documentation is generated by Epydoc and stored in Google Drive, create a wiev
and link with web service: https://drv.tw/

"""
# imports
import numpy as np
from PIL import Image

# Constants.
WIDTH = 5001
HEIGHT = 5001

class Automata(object):
    """Automata,
        
    Class automata for define and instance an basic cellular automata.
    Define a rule to operate and a set of params.
        
    """
    rules = list()

    def __init__(self,idx=0):
        self.idx = idx
        self.state = False
        self.statePrev = False

class World(object):
    """World.
        
    Class world for instance a world where the cellular automatas
    develop the steps based in the received rule, using the Wolfarm Code.
        
    """
    
    def __init__(self,rule=50):
        # Define the  params of world, like dimensions and automata rules.
        
        self.rule = rule
        self.im = Image.new("L",(WIDTH,HEIGHT))
        self.data = np.zeros(WIDTH*HEIGHT,dtype=np.uint8)
        b = bin(rule)[2:].zfill(8)
        Automata.rules = [True if c == "1" else False for c in b]
        print((Automata.rules))
        self.list = list()
        self.step = 0
    
    def add(self):
        # Add the  automata to list to operate
        
        automata = Automata(len(self.list))
        self.list.append(automata)

    def update(self):
        # Update the state of the list of automatas to evolve in time
        
        for automata in self.list:
            # Evaluate the conditions against rules.
            
            automata.statePrev = automata.state
            p = self.list[automata.idx - 1].statePrev if automata.idx > 0 else False
            n = self.list[automata.idx + 1].state if automata.idx < len(self.list)-1 else False
            s = automata.state

            if p and s and n:
                automata.state = automata.rules[0]
            elif p and s and not n:
                automata.state = automata.rules[1]
            elif p and not s and n:
                automata.state = automata.rules[2]
            elif p and not s and not n:
                automata.state = automata.rules[3]
            elif not p and s and n:
                automata.state = automata.rules[4]
            elif not p and s and not n:
                automata.state = automata.rules[5]
            elif not p and not s and n:
                automata.state = automata.rules[6]
            elif not p and not s and not n:
                automata.state = automata.rules[7]
            

    def draw_row(self):
        # Draw every row for develop the world in clock time
        
        if self.step == 0:
            middle = (len(self.list) // 2)
            self.list[middle].state = True
        for i,automata in enumerate(self.list):
            if automata.state:
                self.data[self.step*HEIGHT+i] = 255
        self.step += 1
    def save(self):
        self.im.putdata(self.data)
        self.im.save("RULE-%d.png" % self.rule)
    def __str__(self):
        s = str()
        for l in self.list:
            s += "T" if l.state else "F"
        return s

def world_run(rule):
    # Call the instance and give the rule and apply the constants like limits
    world = World(rule)
    for _ in range(WIDTH):
        world.add()

    for _ in range(HEIGHT):
        world.draw_row()
        world.update()
    world.save()

def main():
    # Start the program and get a rule from user
    rule = eval(input("Rule: "))
    try:
        rule = int(rule)
        if 255 >= rule >= 0:
            world_run(rule)
            print(("Check for the generated RULE-%d.png file" % rule))
        else:
            raise ValueError
    except ValueError:
        print("Please, insert a number between 0 and 255")
        main()

if __name__ == "__main__":
    main()